version: 2.1

refs:
  filter_branch_testing: &filter_branch_testing
    filters:
      branches:
        only: [testing]

workflows:
  cd:
    jobs:
      - validate

      - publish:
          name: publish-dev
          tag: dev:testing
          filters: {branches: {only: [integration]}}

      - test_orb_file_changed:    *filter_branch_testing
      - test_orb_no_file_changed: *filter_branch_testing
      - test_orb_on_upstream:     *filter_branch_testing

      - publish:
          name: publish-master
          increment-patch: true
          <<: *filter_branch_testing
          requires:
            - validate
            - test_orb_file_changed
            - test_orb_no_file_changed
            - test_orb_on_upstream

      - publish:
          name: publish-tag
          tag: ${CIRCLE_TAG#v}
          filters:
            tags: {only: '/v[0-9]+(\\.[0-9]+)*/'}
            branches: {ignore: '/.*/'}

orbs:
  multirepo-prod: dnephin/multirepo@0.0.5
  multirepo: dnephin/multirepo@dev:testing
  cli: circleci/circleci-cli@0.1.4


executors:
  bash:
    docker:
    - image: bash:4

commands:
  install-packages:
    steps:
      - run:
          name: "Install packages"
          command: |
            apk add --no-cache --no-progress git openssh curl

  setup:
    steps:
      - run: apk add --no-cache --no-progress git
      - checkout
      - run: test/bin/fake-circleci-agent

jobs:
  publish:
    executor: bash
    parameters:
      tag:
        type: string
        default: dev:testing
      increment-patch:
        type: boolean
        default: false
    steps:
      - install-packages
      - checkout
      - cli/install
      - when:
          condition: << parameters.increment-patch >>
          steps:
            - run: git push origin HEAD:master
            - multirepo-prod/run-job-for-paths:
                paths: orb.yaml
            - run: ./make publish_patch

      - unless:
          condition: << parameters.increment-patch >>
          steps:
            - run: version=<< parameters.tag >> ./make publish
            - run: git push origin HEAD:testing

  validate:
    executor: bash
    steps:
      - install-packages
      - checkout
      - cli/install
      - run: ./make validate

  test_orb_file_changed:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: orb.yaml
      - run: test/bin/expect-no-halt

  test_orb_no_file_changed:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: testdata/no-changes-here
      - run: test/bin/expect-halted

  test_orb_on_upstream:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: orb.yaml
          upstream_branch: $CIRCLE_SHA1
      - run: test/bin/expect-no-halt
