version: 2.1

refs:
  test_filter: &test_filter
    filters:
      branches:
        only: [testing]

workflows:
  version: 2.0

#  publish-dev:
#    jobs:
#      - publish
  master:
    jobs: [validate]

  ci:
    jobs:
      - test_orb_file_changed:    *test_filter
      - test_orb_no_file_changed: *test_filter
      - test_orb_on_upstream:     *test_filter

orbs:
  multirepo: dnephin/multirepo@dev:testing
  cli: circleci/circleci-cli@0.1.4


executors:
  bash:
    docker:
    - image: bash:4

commands:
  install-packages:
    steps:
      - run:
          name: "Install packages"
          command: |
            apk add --no-cache --no-progress git openssh curl

  setup:
    steps:
      - run: apk add --no-cache --no-progress git
      - checkout
      - run: test/bin/fake-circleci-agent

jobs:
  publish:
    executor: bash
    parameters:
      tag:
        type: string
        default: "dev:testing"
    steps:
      - install-packages
      - checkout
      - cli/install
      - run: version=<< parameters.tag >> ./make publish
      - run: |
          git co -b local
          git push origin local:testing

  validate:
    executor: bash
    steps:
      - install-packages
      - checkout
      - cli/install
      - run: ./make validate

  test_orb_file_changed:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: orb.yaml
      - run: test/bin/expect-no-halt

  test_orb_no_file_changed:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: testdata/no-changes-here
      - run: test/bin/expect-halted

  test_orb_on_upstream:
    executor: bash
    environment:
      TESTDIR: /tmp/testdir
    steps:
      - setup
      - multirepo/run-job-for-paths:
          paths: orb.yaml
          upstream_branch: $CIRCLE_SHA1
      - run: test/bin/expect-no-halt
